### PR TITLE
upgraded intl to 19

### PR DESCRIPTION
**Pull request by jhaglund**
## Connection with issue(s)

Close #???
Closes half of 106, but not flutter_type_ahead

Connected to #???

## To Do

- [x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [x] Check the original issue to confirm it is fully satisfied
- [ ] Add solution description to help guide reviewers
- [ ] Add unit test to verify new or fixed behaviour
- [ ] If apply, add documentation to code properties and package readme

### CODE REVIEW

**Comment by deandreamatias** [comment]
Probably need to apply the same things that this PR https://github.com/flutter-form-builder-ecosystem/form_builder_validators/pull/94/files
Mainly 
```dart
environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"
```

**Comment by jhaglund** [comment]
Locally, I additionally changed the pubspec.yaml to point at github's updated form_builder_validators instead of getting from pub.dev. Of course, I didn't check that change in. But it works for me. Pub.dev needs the updated form_builder_validators

**Comment by jhaglund** [comment]
I just realized, the pubspec.yaml points to my github repo to resolve the updated form_builder_validators. I think this will be OK -- local repos will overwrite this as soon as someone runs `pub get` but ideally I guess it form_builder_validators would be in pub.dev. But pubspec.yaml is what matters, so I think it's fine. But worth noting

**Comment by jhaglund** [comment]
I'm getting errors involving flutter_colorpicker, looking into it, don't merge, thanks!

**Comment by jhaglund** [comment]
Ok, after running pub upgrade, the colorpicker problem went away. I think this is OK to merge, but ideally form_builder_validators would be published in pub.dev. Either way works for me, thanks!

**Comment by deandreamatias** [comment]
@jhaglund form_builder_validators version 10.0 with intl 0.19 published

**Comment by Sumit258000** [comment]
@deandreamatias any plans for `intl` dependency upgrade in `form_builder_extra_fields` plugin also? If needed I can make pull request for the same.Thanks.

**Comment by himankBellpost** [comment]
any plans for intl dependency upgrade in form_builder_extra_fields. in how many days we can expect the same?

**Comment by deandreamatias** [comment]
First we need update flutter_form_builder and launch to pub.dev and after that, merge this MR and release a new version

**Comment by deandreamatias** [comment]
I've tried to fix the lints warnings, but I can't modify files that isn't modified by @jhaglund before

**Comment by jhaglund** [comment]
> but I can't modify files that isn't modified by @jhaglund before

@deandreamatias let me know if you need any assistance. I just pushed changes to implement the changes recommended by the `flutter analyze` messages (so build workflow should run without errors)

**Comment by deandreamatias** [comment]
We step forward to next error XD
Now need add to changelog all changes until the last generated release (10.1.0)

**Pull request merged**
